# Generated by Django 5.0.4 on 2024-04-18 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ish_yurituvchi', 'Ish yurituvchi'), ('ishchi', 'Ishchi')], default='ishchi', max_length=255)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to='avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_gone', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_attendance.staff')),
            ],
        ),
    ]
